# Generated by Django 3.1.1 on 2020-09-10 07:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200909_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
